#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0xb98e78a1, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x36916496, __VMLINUX_SYMBOL_STR(inet_csk_reqsk_queue_drop) },
	{ 0x59814a84, __VMLINUX_SYMBOL_STR(dccp_statistics) },
	{ 0x49045426, __VMLINUX_SYMBOL_STR(icmp_err_convert) },
	{ 0x8ef6ecbf, __VMLINUX_SYMBOL_STR(dccp_init_sock) },
	{ 0x5fc56a46, __VMLINUX_SYMBOL_STR(_raw_spin_unlock) },
	{ 0x80d09f28, __VMLINUX_SYMBOL_STR(__ip_route_output_key_hash) },
	{ 0x72fdc791, __VMLINUX_SYMBOL_STR(dccp_set_state) },
	{ 0xce87bdbe, __VMLINUX_SYMBOL_STR(ip_getsockopt) },
	{ 0x2e5810c6, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr1) },
	{ 0x6f53f6a1, __VMLINUX_SYMBOL_STR(inet_unhash) },
	{ 0xa9d618fd, __VMLINUX_SYMBOL_STR(inet_twsk_put) },
	{ 0xb0596156, __VMLINUX_SYMBOL_STR(dccp_hashinfo) },
	{ 0xe2a34cb6, __VMLINUX_SYMBOL_STR(ip_setsockopt) },
	{ 0x18a81be7, __VMLINUX_SYMBOL_STR(dccp_sendmsg) },
	{ 0xd070145e, __VMLINUX_SYMBOL_STR(ip_build_and_send_pkt) },
	{ 0x7d82dfc, __VMLINUX_SYMBOL_STR(sk_setup_caps) },
	{ 0xbc1e059a, __VMLINUX_SYMBOL_STR(dccp_ctl_make_reset) },
	{ 0x9e1c0d0a, __VMLINUX_SYMBOL_STR(dccp_destroy_sock) },
	{ 0x7874831f, __VMLINUX_SYMBOL_STR(dccp_make_response) },
	{ 0xb4daa310, __VMLINUX_SYMBOL_STR(sock_release) },
	{ 0x2de4cd6d, __VMLINUX_SYMBOL_STR(dst_release) },
	{ 0x835ab8ea, __VMLINUX_SYMBOL_STR(dccp_send_sync) },
	{ 0xa88649da, __VMLINUX_SYMBOL_STR(dccp_rcv_established) },
	{ 0xf5c3f5ef, __VMLINUX_SYMBOL_STR(inet_csk_prepare_forced_close) },
	{ 0xe5e4f13a, __VMLINUX_SYMBOL_STR(dccp_create_openreq_child) },
	{ 0xb1ad28e0, __VMLINUX_SYMBOL_STR(__gnu_mcount_nc) },
	{ 0xf91411d9, __VMLINUX_SYMBOL_STR(dccp_check_req) },
	{ 0x55ee84c5, __VMLINUX_SYMBOL_STR(inet_sendmsg) },
	{ 0x84ba6ce4, __VMLINUX_SYMBOL_STR(dccp_recvmsg) },
	{ 0xb769346d, __VMLINUX_SYMBOL_STR(inet_del_protocol) },
	{ 0xd7503f62, __VMLINUX_SYMBOL_STR(inet_sk_rebuild_header) },
	{ 0xc38259af, __VMLINUX_SYMBOL_STR(__this_cpu_preempt_check) },
	{ 0x7d11c268, __VMLINUX_SYMBOL_STR(jiffies) },
	{ 0x66910c85, __VMLINUX_SYMBOL_STR(dccp_ioctl) },
	{ 0x784f2290, __VMLINUX_SYMBOL_STR(dccp_setsockopt) },
	{ 0xbb5a59d0, __VMLINUX_SYMBOL_STR(sock_common_recvmsg) },
	{ 0x2f603042, __VMLINUX_SYMBOL_STR(sock_no_sendpage) },
	{ 0xfb074180, __VMLINUX_SYMBOL_STR(dccp_child_process) },
	{ 0xe55dbc1f, __VMLINUX_SYMBOL_STR(__pskb_pull_tail) },
	{ 0xbf443830, __VMLINUX_SYMBOL_STR(sock_no_mmap) },
	{ 0x5f754e5a, __VMLINUX_SYMBOL_STR(memset) },
	{ 0x7c54b045, __VMLINUX_SYMBOL_STR(sock_no_socketpair) },
	{ 0xbb4d4ed5, __VMLINUX_SYMBOL_STR(skb_checksum) },
	{ 0xef583432, __VMLINUX_SYMBOL_STR(unregister_pernet_subsys) },
	{ 0x80c879d3, __VMLINUX_SYMBOL_STR(dccp_parse_options) },
	{ 0x84fa8761, __VMLINUX_SYMBOL_STR(dccp_getsockopt) },
	{ 0x1ca8f754, __VMLINUX_SYMBOL_STR(inet_csk_update_pmtu) },
	{ 0xcb16ba14, __VMLINUX_SYMBOL_STR(security_sk_classify_flow) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0xb19f51e8, __VMLINUX_SYMBOL_STR(inet_csk_route_req) },
	{ 0x50065ad, __VMLINUX_SYMBOL_STR(inet_csk_route_child_sock) },
	{ 0x140f0736, __VMLINUX_SYMBOL_STR(kmem_cache_free) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0xe8091950, __VMLINUX_SYMBOL_STR(inet_hash_connect) },
	{ 0x38629956, __VMLINUX_SYMBOL_STR(dccp_reqsk_init) },
	{ 0xa3075ef6, __VMLINUX_SYMBOL_STR(dev_get_by_index_rcu) },
	{ 0xbd86f02f, __VMLINUX_SYMBOL_STR(dccp_close) },
	{ 0x257c4699, __VMLINUX_SYMBOL_STR(sk_free) },
	{ 0xd87e2a8e, __VMLINUX_SYMBOL_STR(inet_shutdown) },
	{ 0xd010f124, __VMLINUX_SYMBOL_STR(inet_add_protocol) },
	{ 0x9a123b7, __VMLINUX_SYMBOL_STR(dccp_orphan_count) },
	{ 0x2469810f, __VMLINUX_SYMBOL_STR(__rcu_read_unlock) },
	{ 0x5d2e3f0b, __VMLINUX_SYMBOL_STR(dccp_sync_mss) },
	{ 0xe984e706, __VMLINUX_SYMBOL_STR(inet_accept) },
	{ 0x62bf0ce0, __VMLINUX_SYMBOL_STR(inet_csk_reqsk_queue_drop_and_put) },
	{ 0x5118c382, __VMLINUX_SYMBOL_STR(secure_dccp_sequence_number) },
	{ 0xd13f6b4e, __VMLINUX_SYMBOL_STR(inet_ioctl) },
	{ 0xbaf06326, __VMLINUX_SYMBOL_STR(inet_csk_get_port) },
	{ 0x14b80968, __VMLINUX_SYMBOL_STR(dccp_death_row) },
	{ 0x722d97f4, __VMLINUX_SYMBOL_STR(inet_ctl_sock_create) },
	{ 0x28780949, __VMLINUX_SYMBOL_STR(dccp_poll) },
	{ 0x39127eb3, __VMLINUX_SYMBOL_STR(inet_hash) },
	{ 0xef4719d7, __VMLINUX_SYMBOL_STR(proto_register) },
	{ 0x577027d8, __VMLINUX_SYMBOL_STR(dccp_disconnect) },
	{ 0xe8cae5c5, __VMLINUX_SYMBOL_STR(__sk_dst_check) },
	{ 0x85ebe3ee, __VMLINUX_SYMBOL_STR(inet_release) },
	{ 0x62d42cb2, __VMLINUX_SYMBOL_STR(dccp_done) },
	{ 0xdb7305a1, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0x64a91ba7, __VMLINUX_SYMBOL_STR(inet_reqsk_alloc) },
	{ 0xb6bb9359, __VMLINUX_SYMBOL_STR(kfree_skb) },
	{ 0x3a4f78d5, __VMLINUX_SYMBOL_STR(proto_unregister) },
	{ 0xf0e36f0e, __VMLINUX_SYMBOL_STR(inet_stream_connect) },
	{ 0xb8516c14, __VMLINUX_SYMBOL_STR(inet_getname) },
	{ 0x377eed95, __VMLINUX_SYMBOL_STR(inet_ehash_nolisten) },
	{ 0xf315fec1, __VMLINUX_SYMBOL_STR(register_pernet_subsys) },
	{ 0x5dfcd79d, __VMLINUX_SYMBOL_STR(inet_csk_bind_conflict) },
	{ 0x4cdd391d, __VMLINUX_SYMBOL_STR(dccp_feat_list_purge) },
	{ 0x9c0bd51f, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0xea7adfd2, __VMLINUX_SYMBOL_STR(sk_receive_skb) },
	{ 0x25d1326, __VMLINUX_SYMBOL_STR(inet_csk_reqsk_queue_hash_add) },
	{ 0x2a18c74, __VMLINUX_SYMBOL_STR(nf_conntrack_destroy) },
	{ 0xbdb9d8fc, __VMLINUX_SYMBOL_STR(ip_route_output_flow) },
	{ 0xf6ebc03b, __VMLINUX_SYMBOL_STR(net_ratelimit) },
	{ 0x9d03ac45, __VMLINUX_SYMBOL_STR(sock_common_setsockopt) },
	{ 0x54c754e8, __VMLINUX_SYMBOL_STR(__xfrm_policy_check) },
	{ 0xeb1c7873, __VMLINUX_SYMBOL_STR(inet_register_protosw) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0xe1761617, __VMLINUX_SYMBOL_STR(security_inet_conn_request) },
	{ 0x69ec7f14, __VMLINUX_SYMBOL_STR(inet_dccp_listen) },
	{ 0x5cc41b0c, __VMLINUX_SYMBOL_STR(__inet_inherit_port) },
	{ 0xd7205956, __VMLINUX_SYMBOL_STR(inet_bind) },
	{ 0xbe3ea4b5, __VMLINUX_SYMBOL_STR(sock_common_getsockopt) },
	{ 0x86be7924, __VMLINUX_SYMBOL_STR(dccp_packet_name) },
	{ 0x75fd2cb5, __VMLINUX_SYMBOL_STR(inet_csk_accept) },
	{ 0x8f678b07, __VMLINUX_SYMBOL_STR(__stack_chk_guard) },
	{ 0x1520b095, __VMLINUX_SYMBOL_STR(__inet_lookup_listener) },
	{ 0xddc30d43, __VMLINUX_SYMBOL_STR(dccp_reqsk_send_ack) },
	{ 0xe373ab4b, __VMLINUX_SYMBOL_STR(dccp_rcv_state_process) },
	{ 0x9c3e7d43, __VMLINUX_SYMBOL_STR(dccp_connect) },
	{ 0x71ba56ec, __VMLINUX_SYMBOL_STR(dccp_shutdown) },
	{ 0x8d522714, __VMLINUX_SYMBOL_STR(__rcu_read_lock) },
	{ 0x14768e89, __VMLINUX_SYMBOL_STR(ip_queue_xmit) },
	{ 0x8ef59325, __VMLINUX_SYMBOL_STR(inet_unregister_protosw) },
	{ 0xf1284b7b, __VMLINUX_SYMBOL_STR(inet_csk_addr2sockaddr) },
	{ 0x5078923c, __VMLINUX_SYMBOL_STR(__inet_lookup_established) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=dccp";


MODULE_INFO(srcversion, "B87A538A81961EDC6CE98CD");
