#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0xb98e78a1, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x95d5237e, __VMLINUX_SYMBOL_STR(param_ops_bool) },
	{ 0x53122f0, __VMLINUX_SYMBOL_STR(blk_mq_map_queue) },
	{ 0x71107c01, __VMLINUX_SYMBOL_STR(bus_unregister) },
	{ 0x8375d79d, __VMLINUX_SYMBOL_STR(ida_destroy) },
	{ 0xfd294b84, __VMLINUX_SYMBOL_STR(device_unregister) },
	{ 0x8e04c405, __VMLINUX_SYMBOL_STR(bus_register) },
	{ 0x8c03d20c, __VMLINUX_SYMBOL_STR(destroy_workqueue) },
	{ 0x5c87033c, __VMLINUX_SYMBOL_STR(device_register) },
	{ 0x43a53735, __VMLINUX_SYMBOL_STR(__alloc_workqueue_key) },
	{ 0xac7eadfa, __VMLINUX_SYMBOL_STR(kmem_cache_create) },
	{ 0x466b85b8, __VMLINUX_SYMBOL_STR(libceph_compatible) },
	{ 0xc921ab0b, __VMLINUX_SYMBOL_STR(add_disk) },
	{ 0xc3b56021, __VMLINUX_SYMBOL_STR(device_add) },
	{ 0x8e659150, __VMLINUX_SYMBOL_STR(dev_set_name) },
	{ 0x59e0e58b, __VMLINUX_SYMBOL_STR(blk_queue_max_discard_sectors) },
	{ 0xc6818d44, __VMLINUX_SYMBOL_STR(blk_queue_io_opt) },
	{ 0x4aeb91c0, __VMLINUX_SYMBOL_STR(blk_queue_io_min) },
	{ 0x523c5d81, __VMLINUX_SYMBOL_STR(blk_queue_max_segment_size) },
	{ 0xa97c2ed4, __VMLINUX_SYMBOL_STR(blk_queue_max_segments) },
	{ 0x66fd8e75, __VMLINUX_SYMBOL_STR(blk_queue_max_hw_sectors) },
	{ 0xc07ac827, __VMLINUX_SYMBOL_STR(blk_mq_init_queue) },
	{ 0x9978f095, __VMLINUX_SYMBOL_STR(blk_mq_alloc_tag_set) },
	{ 0x40417b7e, __VMLINUX_SYMBOL_STR(alloc_disk) },
	{ 0x71a50dbc, __VMLINUX_SYMBOL_STR(register_blkdev) },
	{ 0xcbee6439, __VMLINUX_SYMBOL_STR(ida_simple_get) },
	{ 0xaa7b0528, __VMLINUX_SYMBOL_STR(ceph_open_session) },
	{ 0x626dfd2b, __VMLINUX_SYMBOL_STR(ceph_create_client) },
	{ 0x7c9079bb, __VMLINUX_SYMBOL_STR(ceph_monc_wait_osdmap) },
	{ 0xddce3a95, __VMLINUX_SYMBOL_STR(ceph_monc_request_next_osdmap) },
	{ 0xb1dd3414, __VMLINUX_SYMBOL_STR(ceph_monc_do_get_version) },
	{ 0x821b3372, __VMLINUX_SYMBOL_STR(ceph_pg_poolid_by_name) },
	{ 0x4a6b7460, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0xc7672334, __VMLINUX_SYMBOL_STR(ceph_destroy_options) },
	{ 0x7a03887c, __VMLINUX_SYMBOL_STR(ceph_compare_options) },
	{ 0x716aacdf, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0x40e9fb59, __VMLINUX_SYMBOL_STR(ceph_parse_options) },
	{ 0xe2fae716, __VMLINUX_SYMBOL_STR(kmemdup) },
	{ 0x6c1ce5ce, __VMLINUX_SYMBOL_STR(strcspn) },
	{ 0xc7ec6c27, __VMLINUX_SYMBOL_STR(strspn) },
	{ 0x1dd2d14, __VMLINUX_SYMBOL_STR(try_module_get) },
	{ 0xaad1a89a, __VMLINUX_SYMBOL_STR(ceph_pg_pool_name_by_id) },
	{ 0xe2d5255a, __VMLINUX_SYMBOL_STR(strcmp) },
	{ 0x48aaf42d, __VMLINUX_SYMBOL_STR(ceph_osdc_create_event) },
	{ 0x17fa6a7, __VMLINUX_SYMBOL_STR(osd_req_op_cls_request_data_pages) },
	{ 0x4eaa2e0e, __VMLINUX_SYMBOL_STR(blk_mq_end_request) },
	{ 0x6b2e3bcd, __VMLINUX_SYMBOL_STR(ceph_get_snap_context) },
	{ 0xb017d1cd, __VMLINUX_SYMBOL_STR(blk_mq_start_request) },
	{ 0x55651236, __VMLINUX_SYMBOL_STR(osd_req_op_raw_data_in_pages) },
	{ 0x51b63778, __VMLINUX_SYMBOL_STR(fs_bio_set) },
	{ 0xd9f3a960, __VMLINUX_SYMBOL_STR(bio_advance) },
	{ 0x5eb71aa, __VMLINUX_SYMBOL_STR(bio_clone_bioset) },
	{ 0xb81960ca, __VMLINUX_SYMBOL_STR(snprintf) },
	{ 0xdccabe3, __VMLINUX_SYMBOL_STR(osd_req_op_alloc_hint_init) },
	{ 0x3ebff3d9, __VMLINUX_SYMBOL_STR(osd_req_op_extent_osd_data_bio) },
	{ 0x61666a8c, __VMLINUX_SYMBOL_STR(osd_req_op_init) },
	{ 0x41acc91e, __VMLINUX_SYMBOL_STR(__blk_mq_end_request) },
	{ 0xb9163f14, __VMLINUX_SYMBOL_STR(blk_update_request) },
	{ 0x8a2852ab, __VMLINUX_SYMBOL_STR(revalidate_disk) },
	{ 0x3ca81ceb, __VMLINUX_SYMBOL_STR(up_write) },
	{ 0xb1fbfbf1, __VMLINUX_SYMBOL_STR(down_write) },
	{ 0x71c90087, __VMLINUX_SYMBOL_STR(memcmp) },
	{ 0x9f2844a2, __VMLINUX_SYMBOL_STR(osd_req_op_extent_osd_data_pages) },
	{ 0xce04bb9c, __VMLINUX_SYMBOL_STR(osd_req_op_extent_init) },
	{ 0x5f754e5a, __VMLINUX_SYMBOL_STR(memset) },
	{ 0xc499ae1e, __VMLINUX_SYMBOL_STR(kstrdup) },
	{ 0xccc39568, __VMLINUX_SYMBOL_STR(ceph_copy_from_page_vector) },
	{ 0x77aba305, __VMLINUX_SYMBOL_STR(osd_req_op_cls_response_data_pages) },
	{ 0xc4cafeb3, __VMLINUX_SYMBOL_STR(osd_req_op_cls_request_data_pagelist) },
	{ 0xd813625e, __VMLINUX_SYMBOL_STR(ceph_pagelist_append) },
	{ 0x4cdc909, __VMLINUX_SYMBOL_STR(osd_req_op_cls_init) },
	{ 0xa9a6891f, __VMLINUX_SYMBOL_STR(ceph_alloc_page_vector) },
	{ 0xb5a459dc, __VMLINUX_SYMBOL_STR(unregister_blkdev) },
	{ 0x5fdb1e1, __VMLINUX_SYMBOL_STR(device_del) },
	{ 0x5469c7b5, __VMLINUX_SYMBOL_STR(ceph_osdc_flush_notifies) },
	{ 0x996bdb64, __VMLINUX_SYMBOL_STR(_kstrtoul) },
	{ 0x64035d4a, __VMLINUX_SYMBOL_STR(ceph_osdc_cancel_event) },
	{ 0x68a67576, __VMLINUX_SYMBOL_STR(ceph_osdc_set_request_linger) },
	{ 0x8f794a1f, __VMLINUX_SYMBOL_STR(osd_req_op_watch_init) },
	{ 0xba651177, __VMLINUX_SYMBOL_STR(ceph_osdc_alloc_request) },
	{ 0x275ef902, __VMLINUX_SYMBOL_STR(__init_waitqueue_head) },
	{ 0x97255bdf, __VMLINUX_SYMBOL_STR(strlen) },
	{ 0x49ebacbd, __VMLINUX_SYMBOL_STR(_clear_bit) },
	{ 0xf24a32ba, __VMLINUX_SYMBOL_STR(ceph_release_page_vector) },
	{ 0xad669f0e, __VMLINUX_SYMBOL_STR(bio_put) },
	{ 0x140f0736, __VMLINUX_SYMBOL_STR(kmem_cache_free) },
	{ 0xd74bb923, __VMLINUX_SYMBOL_STR(ceph_osdc_put_request) },
	{ 0x6bb8ed40, __VMLINUX_SYMBOL_STR(ceph_osdc_cancel_request) },
	{ 0x6c6cdd4d, __VMLINUX_SYMBOL_STR(wait_for_completion_interruptible_timeout) },
	{ 0x4a51f8cd, __VMLINUX_SYMBOL_STR(put_device) },
	{ 0x7a2add7d, __VMLINUX_SYMBOL_STR(current_kernel_time64) },
	{ 0x1934dc88, __VMLINUX_SYMBOL_STR(ceph_osdc_build_request) },
	{ 0xca54fee, __VMLINUX_SYMBOL_STR(_test_and_set_bit) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0xaa4003b4, __VMLINUX_SYMBOL_STR(get_device) },
	{ 0xb2d48a2e, __VMLINUX_SYMBOL_STR(queue_work_on) },
	{ 0xdcad5081, __VMLINUX_SYMBOL_STR(set_disk_ro) },
	{ 0x1a1431fd, __VMLINUX_SYMBOL_STR(_raw_spin_unlock_irq) },
	{ 0x3507a132, __VMLINUX_SYMBOL_STR(_raw_spin_lock_irq) },
	{ 0x353e3fa5, __VMLINUX_SYMBOL_STR(__get_user_4) },
	{ 0xa4fda575, __VMLINUX_SYMBOL_STR(ceph_client_id) },
	{ 0x91715312, __VMLINUX_SYMBOL_STR(sprintf) },
	{ 0xe914e41e, __VMLINUX_SYMBOL_STR(strcpy) },
	{ 0xab694444, __VMLINUX_SYMBOL_STR(bsearch) },
	{ 0x3f688151, __VMLINUX_SYMBOL_STR(ceph_put_snap_context) },
	{ 0xae3515ba, __VMLINUX_SYMBOL_STR(ceph_create_snap_context) },
	{ 0x9d669763, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0x12da5bb2, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0xd9ce8f0c, __VMLINUX_SYMBOL_STR(strnlen) },
	{ 0x90a8670b, __VMLINUX_SYMBOL_STR(__module_get) },
	{ 0xcc52fcfa, __VMLINUX_SYMBOL_STR(device_initialize) },
	{ 0xdf3cff00, __VMLINUX_SYMBOL_STR(__init_rwsem) },
	{ 0xbf328c0, __VMLINUX_SYMBOL_STR(module_put) },
	{ 0x9c27f2c8, __VMLINUX_SYMBOL_STR(ceph_destroy_client) },
	{ 0x4e3567f7, __VMLINUX_SYMBOL_STR(match_int) },
	{ 0x44e9a829, __VMLINUX_SYMBOL_STR(match_token) },
	{ 0x29e1b020, __VMLINUX_SYMBOL_STR(ida_simple_remove) },
	{ 0x5fc56a46, __VMLINUX_SYMBOL_STR(_raw_spin_unlock) },
	{ 0x9c0bd51f, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0xfe22abf5, __VMLINUX_SYMBOL_STR(put_disk) },
	{ 0x6a86fd1c, __VMLINUX_SYMBOL_STR(blk_mq_free_tag_set) },
	{ 0x5d1b7c02, __VMLINUX_SYMBOL_STR(blk_cleanup_queue) },
	{ 0x25ce3a72, __VMLINUX_SYMBOL_STR(del_gendisk) },
	{ 0xa16e0653, __VMLINUX_SYMBOL_STR(ceph_osdc_start_request) },
	{ 0x81f3afb, __VMLINUX_SYMBOL_STR(complete_all) },
	{ 0x1e047854, __VMLINUX_SYMBOL_STR(warn_slowpath_fmt) },
	{ 0xed93f29e, __VMLINUX_SYMBOL_STR(__kunmap_atomic) },
	{ 0xa15b902, __VMLINUX_SYMBOL_STR(flush_dcache_page) },
	{ 0xfa2a45e, __VMLINUX_SYMBOL_STR(__memzero) },
	{ 0x3ada2992, __VMLINUX_SYMBOL_STR(kmap_atomic) },
	{ 0xa7cab5e6, __VMLINUX_SYMBOL_STR(up_read) },
	{ 0xfc205af9, __VMLINUX_SYMBOL_STR(down_read) },
	{ 0x676bbc0f, __VMLINUX_SYMBOL_STR(_set_bit) },
	{ 0x3ce74a49, __VMLINUX_SYMBOL_STR(kmem_cache_alloc) },
	{ 0x9c2b04fb, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0x3a9cb859, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0xe1844ed8, __VMLINUX_SYMBOL_STR(kmem_cache_destroy) },
	{ 0x8f678b07, __VMLINUX_SYMBOL_STR(__stack_chk_guard) },
	{ 0xdb7305a1, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0x2e5810c6, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr1) },
	{ 0xb1ad28e0, __VMLINUX_SYMBOL_STR(__gnu_mcount_nc) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=";


MODULE_INFO(srcversion, "F1995FF8F94C7C302DEA41F");
